{
 "title": "Sensehat exporter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pi",
    "query": {
     "query": "label_values(sense_hat_version_info,instance)"
    }
   },
   {
    "name": "calibration",
    "query": {
     "query": "label_values(sense_hat_temperature_celsius,calibrated)"
    }
   },
   {
    "name": "humidty_or_pressure",
    "query": {
     "query": "label_values(sense_hat_temperature_celsius,sensor)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sense_hat_temperature_celsius{calibrated=\"$calibration\", sensor=\"$humidty_or_pressure\"}",
     "legendFormat": "Temperature sensor={{sensor}} calibrated={{calibrated}}"
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, sense_hat_relative_humidity_percent{calibrated=\"$calibration\"}[10m])",
     "legendFormat": "Relative humidity calibrated={{calibrated}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, sense_hat_pressure_mbar{instance=\"$pi\", calibrated=\"$calibration\"}[10m])",
     "legendFormat": "Pressure calibrated={{calibrated}}"
    }
   ]
  },
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sense_hat_temperature_celsius{calibrated=\"$calibration\", sensor=\"$humidty_or_pressure\"}",
     "legendFormat": "Temperature sensor={{sensor}} calibrated={{calibrated}}"
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, sense_hat_relative_humidity_percent{calibrated=\"$calibration\"}[10m])",
     "legendFormat": "Relative humidity calibrated={{calibrated}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, sense_hat_pressure_mbar{instance=\"$pi\", calibrated=\"$calibration\"}[10m])",
     "legendFormat": "Pressure calibrated={{calibrated}}"
    }
   ]
  },
  {
   "title": "Calibration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU-environment temperature delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg_over_time(sense_hat_rpi_cpu_temperature_celsius{instance=\"$pi\"}[1h]) - ignoring(calibrated, sensor) quantile_over_time(0.5, sense_hat_temperature_celsius{calibrated=~\"$calibration\", instance=~\"$pi\", sensor=~\"$humidty_or_pressure\"}[1h])",
       "legendFormat": "CPU temp delta"
      }
     ]
    },
    {
     "title": "Temperature calibration value",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sense_hat_temperature_calibration_celsius",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pressure calibration value",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sense_hat_pressure_calibration_mbar",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity calibration value",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sense_hat_humidity_calibration_percent",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}